bike <- readr::read_csv("data-raw/bike.csv") %>%
  tibble::as_tibble() %>%
  dplyr::rename(
    year = yr,
    month = mnth,
    working_day = workingday,
    weather = weathersit,
    temperature = temp,
    humidity = hum,
    bikes_rented = cnt,
    wind_speed = windspeed
  ) %>%
  dplyr::mutate(
    season = forcats::fct_recode(season,
      "Spring" = "SPRING",
      "Summer" = "SUMMER",
      "Autumn" = "FALL",
      "Winter" = "WINTER"),
    month = forcats::fct_recode(month,
      "January" = "JAN",
      "Feburary" = "FEB",
      "March" = "MAR",
      "April" = "APR",
      "May" = "MAY",
      "June" = "JUN",
      "July" = "JUL",
      "August" = "AUG",
      "September" = "SEP",
      "October" = "OKT",
      "November" = "NOV",
      "December" = "DEZ"),
    holiday = forcats::fct_recode(holiday,
      "No" = "NO HOLIDAY",
      "Yes" = "HOLIDAY"),
    weekday = forcats::fct_recode(weekday,
      "Sunday" = "SUN",
      "Monday" = "MON",
      "Tuesday" = "TUE",
      "Wednesday" = "WED",
      "Thursday" = "THU",
      "Friday" = "FRI",
      "Saturday" = "SAT"),
    working_day = forcats::fct_recode(working_day,
      "No" = "NO WORKING DAY",
      "Yes" = "WORKING DAY"),
    weather = forcats::fct_recode(weather,
      "Good" = "GOOD",
      "Misty" = "MISTY",
      "Rain/Snow/Storm" = "RAIN/SNOW/STORM"))

usethis::use_data(bike)
